### ISSUE TITLE
Paulo test 2

### ISSUE THREAD

**Issue by PauloGasparSv** [PauloGasparSv/TestingHooks#17]
Yup

**Comment by PauloGasparSv** [comment]
Congrats @JmillsExpensify, you've been assigned to help with this important E.org task! Please refer to [this SO](https://stackoverflow.com/c/expensify/questions/13791/13792#13792).

**Comment by JmillsExpensify** [comment]
Was catching up on old issues. I think we should close this one right? I'm going to go ahead and do that but please re-open if I'm mistaken.

**Comment by JmillsExpensify** [comment]
Oh haha this is in your own repo. Nevermind.

**Comment by PauloGasparSv** [comment]
Hahaha just saw this now @JmillsExpensify, forgot to reply about this :D
